### ISSUE TITLE
[Feature]: Research about graph database & start implementation

### ISSUE THREAD

**Issue by LayBraid** [PoCInnovation/Discover#11]
### Description

You need to research which database to implement and give the right and wrong arguments. Then you should start implementing your chosen solution.

### Expected behaviour

/

### Environment

/

### Proposed solution

Check this: https://www.tigergraph.com/

**Comment by agherasie** [comment]
- to compare with : https://neo4j.com/fr/

which is better @Tipbs ? what are the pros and cons of each / differences
